apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-env
data:
  APP_NAME: "profile"
  APP_ENV: "prod"
  GRPC_PORT: "50051"

  DATABASE_URL: "postgresql://postgres:postgres@pgbouncer:5432/profile"
  DATABASE_DIRECT_URL: "postgresql://postgres:postgres@postgres:5432/profile"

  PG_BOSS_MAX: "5"
  PG_BOSS_MAINTENANCE_INTERVAL_SECONDS: "60"
  PG_BOSS_APPLICATION_NAME: "profile-pg-boss"

  KAFKA_BROKERS: "kafka:9092"
  KAFKA_CLIENT_ID: "profile-client"

  MESSAGE_PRODUCER_TOPIC_BATTLE_MATCHED: "profile.matched"
  MESSAGE_CONSUMER_TOPIC_BATTLE_UPDATED: "engine.profile_updated"
  MESSAGE_CONSUMER_TOPIC_BATTLE_TERMINATED: "engine.profile_terminated"