apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-env
data:
  APP_NAME: "profile"
  APP_ENV: "prod"
  GRPC_PORT: "50051"

  DATABASE_URL: "postgresql://postgres:postgres@pgbouncer:6432/profile"
  DATABASE_DIRECT_URL: "postgresql://postgres:postgres@postgres:5432/profile"

  PG_BOSS_MAX: "5"
  PG_BOSS_MAINTENANCE_INTERVAL_SECONDS: "60"
  PG_BOSS_APPLICATION_NAME: "profile-pg-boss"

  KAFKA_BROKERS: "kafka:9092"
  KAFKA_CLIENT_ID: "profile-client"
  KAFKA_GROUP_ID: "profile-service"
  MESSAGE_CONSUMER_TOPIC_USER_CREATED: "user.created"
  MESSAGE_PRODUCER_TOPIC_PROFILE_CREATED: "profile.created"