apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
spec:
  replicas: 1

  selector:
    matchLabels:
      app: profile

  template:
    metadata:
      labels:
        app: profile

    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret

      containers:
        - name: profile
          image: ghcr.io/beartrando/tic-tac-toe-profile/service

          ports:
            - containerPort: 50051

          envFrom:
            - configMapRef:
                name: profile-env
            - secretRef:
                name: profile-env

          livenessProbe:
            exec:
              command:
                - wget
                - -q
                - --spider
                - http://127.0.0.1:50051
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10

          readinessProbe:
            exec:
              command:
                - wget
                - -q
                - --spider
                - http://127.0.0.1:50051
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10