apiVersion: v1
kind: ConfigMap
metadata:
  name: battle-env
data:
  APP_NAME: "battle"
  APP_ENV: "prod"
  GRPC_PORT: "50051"

  DATABASE_URL: "postgresql://postgres:postgres@pgbouncer:5432/battle"
  DATABASE_DIRECT_URL: "postgresql://postgres:postgres@postgres:5432/battle"

  PG_BOSS_MAX: "5"
  PG_BOSS_MAINTENANCE_INTERVAL_SECONDS: "60"
  PG_BOSS_APPLICATION_NAME: "battle-pg-boss"

  KAFKA_BROKERS: "kafka:9092"
  KAFKA_CLIENT_ID: "battle-client"

  MESSAGE_PRODUCER_TOPIC_BATTLE_MATCHED: "battle.matched"
  MESSAGE_CONSUMER_TOPIC_BATTLE_UPDATED: "engine.battle_updated"
  MESSAGE_CONSUMER_TOPIC_BATTLE_TERMINATED: "engine.battle_terminated"