apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-env
data:
  APP_NAME: "gateway"
  APP_ENV: "prod"

  GRPC_PORT: "50051"
  HTTP_PORT: "9090"

  SERVICE_BOT_URL: "bot:50051"
  SERVICE_AUTH_URL: "auth:50051"
  SERVICE_PROFILE_URL: "profile:50051"
  SERVICE_ORCHESTRATION_URL: "orchestration:50051"
  SERVICE_ENGINE_URL: "engine:50051"
  SERVICE_BATTLE_URL: "battle:50051"
  SERVICE_STREAMING_URL: "streaming:50051"
