syntax = "proto3";

package common.health;
import "common/empty.proto";

service Health {
  rpc Check (common.empty.Empty) returns (HealthReport);
  rpc Status (common.empty.Empty) returns (StatusInfo);
  rpc Livez (common.empty.Empty) returns (LiveStatus);
  rpc Readyz (common.empty.Empty) returns (ReadyStatus);
}

message HealthReport {
//  string service = 1;   // имя сервиса
  map<string, string> components = 2;
  bool healthy = 3;
//  int64 timestamp = 4;  // время отчёта (unix time)

}

message StatusInfo {
  string name = 1;
  string version = 2;
  double uptime = 4;
  string env = 5;
  string timestamp = 6;
}

message LiveStatus {
  bool live = 1;
}

message ReadyStatus {
  bool ready = 1;
}
