syntax = "proto3";

package auth;

import "google/protobuf/timestamp.proto";
import "common/empty.proto";
import "common/error.proto";
import "common/response.proto";

service Auth {
  rpc Register (RegisterRequest) returns (AuthResponse);
  rpc Login (LoginRequest) returns (AuthResponse);
  rpc Logout (common.empty.Empty) returns (common.response.EmptyResponse);
  rpc RefreshTokens (RefreshTokensRequest) returns (AuthResponse);
  rpc ForgotPassword (ForgotPasswordRequest) returns (common.response.EmptyResponse);
  rpc ResetPassword (ResetPasswordRequest) returns (AuthResponse);
  rpc AnonymousSignIn (AnonymousSignInRequest) returns (AuthResponse);
  rpc Get (UserIdRequest) returns (UserResponse);
  rpc GetMe (common.empty.Empty) returns (UserResponse);
}

message RegisterRequest {
  string email    = 1;
  string password = 2;
}

message UserObject {
  string                     id         = 1;
  string                     email      = 2;
  google.protobuf.Timestamp  created_at = 3;
  google.protobuf.Timestamp  updated_at = 4;
}

message UserIdRequest {
  string user_id = 1;
}

message AuthObject {
  string access_token  = 1;
  string refresh_token = 2;
}

message LoginRequest {
  string email    = 1;
  string password = 2;
}

message RefreshTokensRequest {
  string token = 1;
}

message ForgotPasswordRequest {
  string email = 1;
}

message ResetPasswordRequest {
  string token        = 1;
  string new_password = 2;
}

message AnonymousSignInRequest {
  string device_id = 1;
}

message AuthResponse {
  oneof output {
    AuthObject               auth  = 1;
    common.error.ErrorObject error = 2;
  }
}

message UserResponse {
  oneof output {
    UserObject               user  = 1;
    common.error.ErrorObject error = 2;
  }
}
