syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "auth.proto";
import "profile.proto";
//import "google/protobuf/timestamp.proto";

package battle;

service Battle {
  rpc GetActiveByUser (auth.UserIdRequest) returns (BattleObject);
  rpc Get (BattleIdRequest) returns (BattleObject);
  rpc Upsert (profile.ProfileIdRequest) returns (BattleObject);
  rpc Join (StartBattleRequest) returns (BattleObject);
  rpc Leave (BattleLeaveRequest) returns (BattleObject);
}

message BattleIdRequest {
  string battleId = 1;
}

message BattleRequest {
  BattleObject battle = 1;
}

message StartBattleRequest {
  string battleId  = 1;
  string profileId = 2;
}

message BattleLeaveRequest {
  string battleId  = 1;
  string profileId = 2;
}

enum BattleCellValue {
  CELL_EMPTY = 0;
  CELL_X     = 1;
  CELL_O     = 2;
}

enum BattleStatus {
  NEW      = 0;
  ACTIVE   = 1;
  FINISHED = 2;
}

message BattleObject {
  string                    id         = 1;
  repeated BattleCellValue  cells      = 2;
  repeated string           players    = 3;
  BattleStatus              status     = 4;
  string                    winner     = 5;
  google.protobuf.Timestamp lastMoveAt = 6;
  google.protobuf.Timestamp createdAt  = 7;
  google.protobuf.Timestamp updatedAt  = 8;
}


