syntax = "proto3";

package battle;

import "google/protobuf/timestamp.proto";
import "auth.proto";
import "profile.proto";
import "common/error.proto";

service Battle {
  rpc GetActiveByUser (auth.UserIdRequest) returns (BattleResponse);
  rpc Get (BattleIdRequest) returns (BattleResponse);
  rpc GetOrCreate (profile.ProfileIdRequest) returns (BattleResponse);
  rpc Join (BattleStartRequest) returns (BattleResponse);
}

message BattleIdRequest {
  string battle_id = 1;
}

message BattleStartRequest {
  string battle_id  = 1;
  string profile_id = 2;
}

enum BattleCellValue {
  CELL_EMPTY = 0;
  CELL_X     = 1;
  CELL_O     = 2;
}

enum BattleStatus {
  BATTLE_STATUS_UNKNOWN = 0;
  NEW                   = 1;
  ACTIVE                = 2;
  FINISHED              = 3;
}

message BattleObject {
  string                    id           = 1;
  repeated BattleCellValue  cells        = 2;
  repeated string           player_ids   = 3;
  BattleStatus              status       = 4;
  string                    winner_id    = 5;
  google.protobuf.Timestamp last_move_at = 6;
  google.protobuf.Timestamp created_at   = 7;
  google.protobuf.Timestamp updated_at   = 8;
}

message BattleResponse {
  oneof output {
    BattleObject             battle = 1;
    common.error.ErrorObject error  = 2;
  }
}


