syntax = "proto3";

package engine;

import "common/empty.proto";
import "common/error.proto";
import "common/ping.proto";
import "battle.proto";

service Engine {
  rpc BattleChannel (stream BattleRequest) returns (stream BattleResponse);
}

message BattleRequest {
  oneof input {
    battle.BattleObject start      = 1;
    BattleMove          move       = 2;
    BattleLeave         leave      = 3;
    BattleLeave         disconnect = 4;
    common.ping.Ping    ping       = 5;
  }
}

message BattleResponse {
  oneof output {
    battle.BattleObject      battle = 1;
    common.empty.Empty       ping   = 2;
    common.error.ErrorObject error  = 3;
  }
}

message BattleMove {
  string battle_id  = 1;
  string profile_id = 2;
  int32  cell_idx   = 3;
}

message BattleLeave {
  string battle_id  = 1;
  string profile_id = 2;
}
