syntax = "proto3";

import "common/key_value.proto";

package orchestration;

service Orchestration {
  rpc Proxy(ProxyRequest) returns (ProxyResponse);
}

message ProxyRequest {
  string                             method      = 1;
  string                             path        = 2;
  repeated common.key_value.KeyValue headers     = 3;
  repeated common.key_value.KeyValue queryParams = 4;
  bytes                              body        = 5;
}

message ProxyResponse {
  int32                              status  = 1;
  repeated common.key_value.KeyValue headers = 2;
  bytes                              body    = 3;
}
