syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "common/empty.proto";
import "auth.proto";

package profile;

service Profile {
  rpc GetMe (common.empty.Empty) returns (ProfileObject);
  rpc GetByUser (auth.UserIdRequest) returns (ProfileObject);
  rpc Get (profile.ProfileIdRequest) returns (ProfileObject);
  rpc Upsert (auth.UserIdRequest) returns (ProfileObject);
}

message ProfileIdRequest {
  string profile_id = 1;
}

message ProfileObject {
  string                    id         = 1;
  string                    user_id    = 2;
  string                    nickname   = 3;
  int64                     level      = 4;
  int64                     rating     = 5;
  int64                     experience = 6;
  google.protobuf.Timestamp createdAt  = 7;
  google.protobuf.Timestamp updatedAt  = 8;
}
