apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-env
data:
  APP_NAME: "streaming"
  APP_ENV: "prod"
  GRPC_PORT: "50051"
  WEBSOCKET_PORT: "8080"

  DATABASE_URL: "postgresql://postgres:postgres@pgbouncer:5432/streaming"
  DATABASE_DIRECT_URL: "postgresql://postgres:postgres@postgres:5432/streaming"

  SERVICE_AUTH_URL: "auth:50051"
  SERVICE_PROFILE_URL: "profile:50051"
  SERVICE_ENGINE_URL: "engine:50051"
  SERVICE_BATTLE_URL: "battle:50051"

  RABBIT_HOST: "rabbitmq"
  RABBIT_USER: "user"
  RABBIT_PASS: "password"

  IDDLE_WEBSOCKET_TIME_LIMIT: "300"

  PG_BOSS_MAX: "5"
  PG_BOSS_MAINTENANCE_INTERVAL_SECONDS: "60"
  PG_BOSS_APPLICATION_NAME: "streaming-pg-boss"

  KAFKA_BROKERS: "kafka:9092"
  KAFKA_CLIENT_ID: "streaming-client"
  MESSAGE_PRODUCER_TOPIC_BOT_CONNECTING_REQUEST: "bot.connecting-request"