apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-env
data:
  APP_NAME: "auth"
  APP_ENV: "prod"

  GRPC_PORT: "50051"

  DATABASE_URL: "postgresql://postgres:postgres@pgbouncer:6432/auth"
  DATABASE_DIRECT_URL: "postgresql://postgres:postgres@postgres:5432/auth"

  ACCESS_TOKEN_EXPIRES_IN: "1h"
  REFRESH_TOKEN_EXPIRES_IN: "7d"

  PG_BOSS_MAX: "5"
  PG_BOSS_MAINTENANCE_INTERVAL_SECONDS: "60"
  PG_BOSS_APPLICATION_NAME: "auth-pg-boss"

  KAFKA_BROKERS: "kafka:9092"
  KAFKA_CLIENT_ID: "auth-client"
  MESSAGE_PRODUCER_TOPIC_USER_CREATED: "user.created"
