apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-env
data:
  APP_NAME: "bot"
  APP_ENV: "prod"
  GRPC_PORT: "50051"

  HTTP_GATEWAY: "gateway:9090"
  WEBSOCKET_STREAMING: "streaming:8080"

  DATABASE_URL: "postgresql://postgres:postgres@pgbouncer:6432/bot"
  DATABASE_DIRECT_URL: "postgresql://postgres:postgres@postgres:5432/bot"

  KAFKA_BROKERS: "kafka:9092"
  KAFKA_CLIENT_ID: "bot-client"
  MESSAGE_CONSUMER_TOPIC_AI_CONNECTING_REQUEST: "bot.connecting-request"

  PG_BOSS_WEBSOCKET_SEND_EVENT: "pg-boss.websocket-send-event"
  PG_BOSS_MAX: "5"
  PG_BOSS_MAINTENANCE_INTERVAL_SECONDS: "60"
  PG_BOSS_APPLICATION_NAME: "bot-pg-boss"

  DEVICE_ID: "bot-device-id"