apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tic-tac-toe

resources:
  - namespace.yaml
  - infrastructure/postgres/statefulset.yaml
  - infrastructure/postgres/service.yaml
